---
title: "flat_minimal.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# get_info_data
    
```{r function-get_info_data}
#' This function gives the info on the dataframe
#' @param data dataframe
#' 
#' @return return list of 2 :- dimension and fields of the dataframe
#' 
#' @export
get_info_data <- function(data){
  if (isFALSE(is.data.frame(data))){
    stop("The argument `data` must be a data frame")
  }
  res <- list(
    dimension = dim(data),
    names = names(data)
  )
  return(res)

}
```
  
```{r example-get_info_data}
get_info_data(data = iris)
```
  
```{r tests-get_info_data}
test_that("get_info_data works", {
  expect_equal(
    object = get_info_data(data = iris),
    # Output of `get_info_data(data = iris) %>% dput()`
    expected = list(
      dimension = c(150L, 5L),
      names = c(
        "Sepal.Length",
        "Sepal.Width",
        "Petal.Length",
        "Petal.Width",
        "Species"
      )
    )
  )
  
  expect_error(
    object = get_info_data("mydata"), 
    regexp = "The argument `data` must be a data frame"
  )
})
```
  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_minimal.Rmd", vignette_name = "Minimal")
```
