# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

test_that("get_info_data works", {
  expect_equal(
    object = get_info_data(data = iris),
    # Output of `get_info_data(data = iris) %>% dput()`
    expected = list(
      dimension = c(150L, 5L),
      names = c(
        "Sepal.Length",
        "Sepal.Width",
        "Petal.Length",
        "Petal.Width",
        "Species"
      )
    )
  )
  
  expect_error(
    object = get_info_data("mydata"), 
    regexp = "The argument `data` must be a data frame"
  )
})
