# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' This function gives the info on the dataframe
#' 
#' 
#' @return
#' 
#' @export
#' @examples
#' get_info_data(data = iris)
get_info_data <- function(data){
    print(dim(data))
    print(colnames(data))
}
