# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' This function gives the info on the dataframe
#' @param data dataframe
#' 
#' @return return list of 2 :- dimension and fields of the dataframe
#' 
#' @export
#' @examples
#' get_info_data(data = iris)
get_info_data <- function(data){
  if (isFALSE(is.data.frame(data))){
    stop("The argument `data` must be a data frame")
  }
  res <- list(
    dimension = dim(data),
    names = names(data)
  )
  return(res)

}
